### ISSUE TITLE
Add manifest for PWA

### ISSUE THREAD

**Issue by stritti** [ghys/habot#10]
For better PWA-support I think HABot should add a manifest.json.

For further Information, see e.g. https://docs.pwabuilder.com/what/is/a/pwa/2018/02/03/what-is-a-manifest.html

**Comment by ghys** [comment]
There's a manifest of course, it wouldn't be a PWA at all without one :)
It's generated during the build phase by the sw-precache-webpack-plugin.

By the way, the Lighthouse audit score is 91 (used to be 100 but now that I added the charts and moment.js it's got a bit fat and the initial caching is apparently a little too slow on 3G)

![image](https://user-images.githubusercontent.com/2004147/38266853-0a3bc450-377a-11e8-8fc1-308bcfca2c5b.png)

**Comment by stritti** [comment]
ups, what a shame. Should have deeper look bevor shooting ...
