### ISSUE TITLE
Switch

### ISSUE THREAD

**Issue by jensfr1** [ghys/habot#6]
Hi, 

I am playing a bit with the bot and  now I can switch lights on and off.  

The issue is that the switch in the chat is only visible for the first light I have added. 
<img width="529" alt="2018-03-24 22_19_09-habot" src="https://user-images.githubusercontent.com/12272992/37869074-8417c8da-2fb1-11e8-9c7f-d48bb05ee0a5.png">

Item code for all lights are the same: 
`Switch	Light1_Toggle 		"TV"			<light> (LivingRoom, gLight)   ["object:tvlicht", "object:licht", "object:light", "object:lights", "object:lighting"]	{ channel="hue:" } 
Switch	Light2_Toggle 		"Stehlampe"		<light> (LivingRoom, gLight)   ["object:stehlampe", "object:licht", "object:light", "object:lights", "object:lighting"]	{ channel="hue:" }
`

In the Card Board I can also not find it. 
<img width="1271" alt="2018-03-24 22_26_48-habot" src="https://user-images.githubusercontent.com/12272992/37869140-a48223da-2fb2-11e8-8bec-e141429b1573.png">

In the Items Menu in settings for example I dont find Light2 even it is in the items file and in the Paper UI.
<img width="1019" alt="2018-03-24 22_23_39-habot" src="https://user-images.githubusercontent.com/12272992/37869109-23a82778-2fb2-11e8-8a56-620415e2cee0.png">

Screen from Paper UI. 
<img width="977" alt="2018-03-24 22_24_51-paper ui" src="https://user-images.githubusercontent.com/12272992/37869117-3d631b64-2fb2-11e8-83c5-438706aacb6a.png">

**Comment by ghys** [comment]
Thanks for trying it out!
Hmm, that's odd. It looks like the server-side found all your items alright, but the web client doesn't know about them. It loads the list early on via a call to the `rest/items` API - same as Paper UI.

Here are a couple suggestions:
- Open the developer tools (F12 on Windows), refresh the HABot page (F5) and check if there are any errors appearing in the Console tab.
- Go to `http://openhab:8080/rest/items` manually and verify the items appear (Ctrl-F the name)

**Comment by jensfr1** [comment]
Is really odd but once I stopped sitting at my desk and moved to the sofa it worked from my phone and now also in Chrome.
Cheers, Jens

**Comment by ghys** [comment]
Could be because the items weren't there when you displayed the page, and you didn't refresh the page?
If the items change the UI doesn't know about it (not that it couldn't, there are events sent for that sort of thing, but they are not handled currently).
Anyways, glad it's working now.
