### ISSUE TITLE
Duplicate Entries in Cards

### ISSUE THREAD

**Issue by stritti** [ghys/habot#7]
Sometimes I receive duplicate entries within the answers:

![image](https://user-images.githubusercontent.com/184547/38094644-a287f072-336e-11e8-8424-1373c4f84da8.png)

The second and third value are identical. I think it should be great if the values are distinct.

**Comment by ghys** [comment]
Huh, weird indeed.
I suppose what happens is that you have set the same tag both on the item and a parent group so it matches twice. You can verify on the "View item tags" screen in the settings.
Anyways it can be fixed easily. Thanks for reporting!

**Comment by ghys** [comment]
This should be fixed in https://github.com/ghys/habot/releases/tag/2.3.0.201804021654

**Comment by stritti** [comment]
Looks fine. Thanks!
